### ISSUE TITLE
bug: Pressing 'e' does not open text editor

### ISSUE THREAD

**Issue by SchoolyB** [thabetx/dima#1]
After running `odin build main && ./main.bin` the program opens and runs successfully but when I press 'e' nothing happens. Not sure why that is. I am on Linux but cant imagine that having anything to with it.

## Specs:
OS: Ubuntu 22.04.4LTS
Processor: 12th Gen Intel Core i3
Ram: 8gb

**Comment by thabetx** [comment]
This should be fixed now if you pull the latest commits.

The problem was executing commands wasn't supported on Linux but it's supported now.

Thanks for the report.
